apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
spec:
  selector:
    app: api-management
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP