name: CI Pipeline for Kubernetes + OpenTelemetry + LocalStack

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Kubernetes with Kind
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: "ci-cluster"

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f kubernetes-poc/poc-deployment.yaml
          sleep 10 

      - name: Verify Kubernetes Pods
        run: kubectl get pods -n observability
