name: CI Pipeline for API Gateway

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Kubernetes with Kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/
          kind create cluster --name ci-cluster

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update Helm Dependencies
        run: |
          helm dependency update ./helm
          sleep 10

      - name: Deploy API Gateway (APISIX)
        run: |
          helm upgrade --install apisix ./helm -n apisix --create-namespace --wait

      - name: Verify Kubernetes Pods
        run: kubectl get pods -n apisix

      - name: Port-Forward API Gateway
        run: kubectl port-forward -n apisix svc/apisix-gateway 9080:80 &

      - name: Test API Gateway
        run: |
          curl --location --request GET "localhost:9080/get?foo1=bar1&foo2=bar2" -H "Host: local.httpbin.org"
