name: CI Pipeline for Kubernetes + OpenTelemetry + LocalStack

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Kubernetes with Kind
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: "ci-cluster"

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f kubernetes-poc/poc-deployment.yaml
          sleep 10 

      - name: Verify Kubernetes Pods
        run: kubectl get pods -n observability

      - name: Port-Forward LocalStack
        run: kubectl port-forward -n observability svc/localstack 4566:4566 &

      - name: Verify LocalStack
        run: aws --endpoint-url=http://localhost:4566 s3 ls

      - name: Create S3 Bucket
        run: aws --endpoint-url=http://localhost:4566 s3 mb s3://otel-traces

      - name: Verify S3 Bucket
        run: aws --endpoint-url=http://localhost:4566 s3 ls

      - name: Port-Forward OpenTelemetry Collector
        run: kubectl port-forward -n observability svc/otel-collector 4317:4317 &

      - name: Install otel-cli
        run: |
          curl -L https://github.com/equinix-labs/otel-cli/releases/latest/download/otel-cli-linux-amd64 -o otel-cli
          ls -l otel-cli
          chmod +x otel-cli
          sudo mv otel-cli /usr/local/bin/

      - name: Verify otel-cli installation
        run: |
          ls -l /usr/local/bin/otel-cli
          otel-cli --version
            
      - name: Send Test Trace
        run: otel-cli span --name "test-span" --endpoint http://localhost:4317 --protocol grpc --verbose

      - name: Verify Trace in S3
        run: aws --endpoint-url=http://localhost:4566 s3 ls s3://otel-traces --recursive
